Demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Demo.PL.Helper;
using Demo.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Runtime.Serialization.Formatters;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public EmployeeController(IUnitOfWork unitOfWork,IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        public IActionResult Index(string SearchValue = "")
        {

            ViewBag.SearchValue = string.IsNullOrEmpty(SearchValue) ? "": SearchValue;
            IEnumerable<Employee> employees;

            if (string.IsNullOrEmpty(SearchValue))
                employees = _unitOfWork.EmployeeRepository.GetAll();
            else
                employees = _unitOfWork.EmployeeRepository.Search(SearchValue);
            var demployeeViewModel = _mapper.Map<IEnumerable<EmployeeViewModel>>(employees);
            return View("Index", demployeeViewModel);
        }

        public IActionResult Create()
        {
            ViewBag.Departments = _mapper.Map<IEnumerable<DepartmentViewModel>>(_unitOfWork.DepartmentRepository.GetAll());
            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeViewModel employeeViewModel)
        {
            if (ModelState.IsValid)
            {
                var employee = _mapper.Map<Employee>(employeeViewModel);
                employee.ImageUrl = DocumentSettings.UploadFile(employeeViewModel.Image, "Images/Employees");

                _unitOfWork.EmployeeRepository.Add(employee);
                _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Departments = _mapper.Map<IEnumerable<DepartmentViewModel>>(_unitOfWork.DepartmentRepository.GetAll());
            return View(employeeViewModel);
        }
        public IActionResult Details(int? id)
        {
            if (id is null)
                return BadRequest();

            var employeeViewModel = _mapper.Map<EmployeeViewModel>(_unitOfWork.EmployeeRepository.GetById(id));
            if (employeeViewModel == null)
                return NotFound();

            ViewBag.DepartmentName = _unitOfWork.EmployeeRepository.GetEmployeeDepartmentName(employeeViewModel.DepartmentId);

            return View(employeeViewModel);
        }
        public IActionResult Update(int? id)
        {
            if (id is null)
                return BadRequest();
            var employeeViewModel = _mapper.Map<EmployeeViewModel>(_unitOfWork.EmployeeRepository.GetById(id));
            if (employeeViewModel is null)
                return NotFound();
            ViewBag.Departments = _mapper.Map<IEnumerable<DepartmentViewModel>>(_unitOfWork.DepartmentRepository.GetAll());

            return View(employeeViewModel);
        }
        [HttpPost]
        public IActionResult Update(int id, EmployeeViewModel employeeViewModel)
        {
            if (id != employeeViewModel.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                var employee = _mapper.Map<Employee>(employeeViewModel);
                
                if (employeeViewModel.Image is not null)
                {
                    DocumentSettings.RemoveFile(employee.ImageUrl, "Images/Employees");
                    employee.ImageUrl = DocumentSettings.UploadFile(employeeViewModel.Image, "Images/Employees");
                }
               

                _unitOfWork.EmployeeRepository.Update(employee);
                _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Departments = _mapper.Map<IEnumerable<DepartmentViewModel>>(_unitOfWork.DepartmentRepository.GetAll());
            return View(employeeViewModel);
        }

        [HttpPost]
        public JsonResult Delete(int? id)
        {
            if (id is null)
                return Json(new { Message = "You must send id", Status = 400 });
            Employee employee = _unitOfWork.EmployeeRepository.GetById(id);

            if (employee is null)
                return Json(new { Message = "There isn't Employee with this Id", Status = 400 });
            _unitOfWork.EmployeeRepository.Delete(employee);
            DocumentSettings.RemoveFile(employee.ImageUrl, "Images/Employees");

            _unitOfWork.Complete();
            return Json(new { Message = "Success", Status = 200 });
        }

    }
}

Demo.PL/Controllers/RoleController.cs
using AutoMapper;
using Demo.DAL.Entities;
using Demo.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace Demo.PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class RoleController : Controller
    {
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;
        private readonly ILogger<RoleController> _logger;

        public RoleController(
            RoleManager<ApplicationRole> roleManager,
            UserManager<ApplicationUser> userManager,
            IMapper mapper,
            ILogger<RoleController> logger)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _mapper = mapper;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            var roleViewModel = _mapper.Map<List<RoleViewModel>>(roles);
            return View(roleViewModel);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel roleViewModel)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var role = new ApplicationRole
                    {
                        Name = roleViewModel.Name,
                        NormalizedName = roleViewModel.Name.ToUpper(),
                    };
                    var result = await _roleManager.CreateAsync(role);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            _logger.LogError(error.Description);
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error: {ex}");
                }

            }
            return View(roleViewModel);
        }

        public async Task<IActionResult> getData(string id,string viewName)
        {
            if(String.IsNullOrEmpty(id))
                return NotFound();
            var role = await _roleManager.FindByIdAsync(id);
            if(role is null)
                return NotFound();
            var roleViewModel = new RoleViewModel
            {
                Id = id,
                Name = role.Name,
                CreateAt = role.CreateAt
            };
            return View(viewName,roleViewModel);
        }
        public async Task<IActionResult> Update(string id)
        {
            return await getData(id, "Update");
        }
        [HttpPost]
        public async Task<IActionResult> Update(string id, RoleViewModel roleViewModel)
        {
            if (id != roleViewModel.Id)
                return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);

                    if (role is null)
                        return NotFound();
                    else
                    {
                        role.Name = roleViewModel.Name;
                        role.NormalizedName = roleViewModel.Name.ToUpper();
                        var result = await _roleManager.UpdateAsync(role);
                        if (result.Succeeded)
                            return RedirectToAction("Index");
                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                _logger.LogError(error.Description);
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error: {ex.Message}");
                }
            }

            return View(roleViewModel);
        }
        public async Task<IActionResult> Details(string id)
        {
            return await getData(id, "Details");
        }
        [HttpPost]
        public async Task<JsonResult> Delete(string? id)
        {

            if (String.IsNullOrEmpty(id))
                return Json(new { Message = "You must send id", Status = 400 });
            var user = await _roleManager.FindByIdAsync(id);
            if (user is null)
                return Json(new { Message = "There isn't Role with this Id", Status = 400 });

            var result = await _roleManager.DeleteAsync(user);
            if (result.Succeeded)
                return Json(new { Message = "Success", Status = 200 });
            else
                return Json(new { Message = result.Errors, Status = 401 });
        }
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            ViewBag.RoleId = roleId;
            if (String.IsNullOrEmpty(roleId))
                return NotFound();
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();
            var usersInRole = new List<UserInRoleViewModel>();
            var users = await _userManager.Users.ToListAsync();
            foreach (var user in users)
            {
                usersInRole.Add( new UserInRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    IsSelected = await _userManager.IsInRoleAsync(user, role.Name),
                });
            }
            return View(usersInRole);
        }
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId, List<UserInRoleViewModel> users)
        {
            ViewBag.RoleId = roleId;
            var role = await _roleManager.FindByIdAsync(roleId);
            if(role is null)
                return NotFound();
            if(ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);
                    if(appUser is not null)
                    {
                        bool userInRole = await _userManager.IsInRoleAsync(appUser, role.Name);
                        if (user.IsSelected && !userInRole)
                            await _userManager.AddToRoleAsync(appUser, role.Name);
                        else if(!user.IsSelected && userInRole)
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);
                    }

                }
                return RedirectToAction("Update", new {id= roleId });
            }
            return View(users);
        }
    }
}

Demo.PL/Controllers/UserController.cs
using AutoMapper;
using Demo.DAL.Entities;
using Demo.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;
        private readonly ILogger<UserController> _logger;

        public UserController(
            UserManager<ApplicationUser> userManager,
            IMapper mapper,
            ILogger<UserController> logger)
        {
            _userManager = userManager;
            _mapper = mapper;
            _logger = logger;
        }
        public async Task<IActionResult> Index(string SearchValue = "") 
        {
            ViewBag.SearchValue = string.IsNullOrEmpty(SearchValue) ? "" : SearchValue;
            IEnumerable<ApplicationUser> users;
            if (String.IsNullOrEmpty(SearchValue))
                users = await _userManager.Users.ToListAsync();
            else
                users = await _userManager.Users.Where(u=>
                                                            u.NormalizedEmail.Trim().Contains(SearchValue.ToUpper().Trim())
                                                           || u.NormalizedUserName.Trim().Contains(SearchValue.ToUpper().Trim())).ToListAsync();

            var usersViewModel = _mapper.Map<List<UserViewModel>>(users);
            return View(usersViewModel);
        }

        public async Task<IActionResult> getData(string id,string viewName)
        {
            if (String.IsNullOrEmpty(id))
                return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if(user is null) 
                return NotFound();
            var userViewModel = new UserViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email,
            };
            return View(viewName, userViewModel);

        } 
        public async Task<IActionResult> Details(string id)
        {
            return await getData(id, "Details");
        }
        public async Task<IActionResult> Update(string id)
        {
            return await getData(id, "Update");
        }
        [HttpPost]
        public async Task<IActionResult> Update(string id,UserViewModel userViewModel)
        {
            if(id !=  userViewModel.Id)
                return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(id);
                    if(user is null)
                        return NotFound();
                    else
                    {
                        user.UserName = userViewModel.UserName;
                        user.NormalizedUserName = userViewModel.UserName.ToUpper();
                        var result = await _userManager.UpdateAsync(user);
                        if (result.Succeeded)
                            return RedirectToAction("Index");
                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                _logger.LogError(error.Description);
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error: {ex.Message}");
                }
            }
            return View(userViewModel);
        }
        [HttpPost]
        public async Task<JsonResult> Delete(string? id)
        {
            
            if(String.IsNullOrEmpty(id))
                return Json(new { Message = "You must send id", Status = 400 });
            var user = await _userManager.FindByIdAsync(id);
            if (user is  null)
                return Json(new { Message = "There isn't User with this Id", Status = 400 });

            var result = await _userManager.DeleteAsync(user);
            if(result.Succeeded)
                return Json(new { Message = "Success", Status = 200 });
            else
                return Json(new { Message = result.Errors, Status = 401 });
        }
    }
}

Demo.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>@ViewData["Title"]</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<!-- Custom Theme files -->
	<link href="~/css/Authstyle.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>@ViewData["Title"]</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
				@RenderBody()
			</div>
		</div>
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Bahrawycodo . All rights reserved | Design by <a href="https://bahrawycodo.com/" target="_blank">BahrawyCodo</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/Authsite.js" asp-append-version="true"></script>
	<partial name="_ValidationScriptsPartial" />

	@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Demo.PL/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/fontawesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                  
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
      <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                      
                        }

                    </ul>
                    @if (signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-light btn btn-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert/js/sweetalert.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Demo.PL/Views/Shared/_TableButtonsPartial.cshtml
@model object
<td><a  asp-action="Details" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-eye"></i> Details</a></td>
<td><a  asp-action="Update" asp-route-id="@Model" class="btn btn-warning"><i class="fas fa-edit"></i> Update</a></td>
@*<td><a  asp-action="Delete" asp-route-id="@Model" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a></td>*@
<td><button type="button" class="btn btn-danger" onclick="deleteItem('@Model',this)"><i class="fas fa-trash"></i> Delete</button></td>